<?php

namespace Database\Seeders;

use App\Models\Research;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ResearchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $penelitian = [
            [
                'category_id' => 2,
                'author' => 'IQBAL RAMADHANI MUKHLIS',
                'title' => 'SEGMENTASI PELANGGAN PADA XYZ AESTHETIC CLINIC',
                'topic_id' => 3,
                'funding' => 'INTERNAL (PDUPT)',
                'year' => 2024,
                'fund' => 5000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'IQBAL RAMADHANI MUKHLIS',
                'title' => 'TATA KELOLA SMART FOREST BUSINESS: TAHAPAN MENUJU SMART TOURISM',
                'topic_id' => 5,
                'funding' => 'Penelitian Kompetitif Nasional (PFR)',
                'year' => 2024,
                'fund' => 129670000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'TRI LATHIF MARDI SURYANTO',
                'title' => 'SUSTAINABLE TOURISM VILLAGE (STV): PEMETAAN KOLABORATIF DI KAWASAN JALUR LINTAS SELATAN (JIS)',
                'topic_id' => 5,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (KELOMPOK RISET)',
                'year' => 2024,
                'fund' => 17000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'TRI LATHIF MARDI SURYANTO',
                'title' => 'ADOPSI AI SEBAGAI FAKTOR KESADARAN BELAJAR MANDIRI BAGI SISWA SMAN PASURUAN',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (PENELITIAN SKRIPSI)',
                'year' => 2024,
                'fund' => 10000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'TRI LATHIF MARDI SURYANTO',
                'title' => 'PENGEMBANGAN DAN PENERAPAN APLIKASI MUSEUM VIRTUAL INDONESIA (SIMVONI) PADA MUSEUM 10 NOPEMBER DAN MONUMEN TUGU PAHLAWAN SURABAYA',
                'topic_id' => 5,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2022,
                'fund' => 22500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'TRI LATHIF MARDI SURYANTO',
                'title' => 'Rancang Bangun Football Scout Performance Analyze Assistant (FORZA)',
                'topic_id' => 6,
                'funding' => 'Penelitian Kompetitif Nasional (PDKN)',
                'year' => 2022,
                'fund' => 87900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'TRI LATHIF MARDI SURYANTO',
                'title' => 'PENERAPAN APLIKASI MUSEUM VIRTUAL INDONESIA (SIMVONI) PADA MUSEUM MPU TANTULAR JAWA TIMUR',
                'topic_id' => 5,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2021,
                'fund' => 25000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'RIZKA HADIWIYANTI',
                'title' => 'MODEL SISTEM PERANGKAT LUNAK GAMIFIKASI YANG MENGOPTIMALKAN RANAH PEMBELAJARAN KOGNITIF, AFEKTIF, DAN SENSORIMOTOR',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (KELOMPOK RISET)',
                'year' => 2024,
                'fund' => 17500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'RIZKA HADIWIYANTI',
                'title' => 'PENGEMBANGAN ALAT UKUR TINGKAT STRESS ATLET DISABILITAS BERBASIS MOBILE APPS BAGI PELATIH',
                'topic_id' => 6,
                'funding' => 'RISET DAN INOVASI UNTUK INDONESIA MAJU (RIIM BRIN)',
                'year' => 2023,
                'fund' => 65000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'RIZKA HADIWIYANTI',
                'title' => 'PENERAPAN SISTEM INFORMASI MANAJEMEN NILAI SISWA (SIMANIS) PADA SEKOLAH DASAR ISLAM TAMAN AN-NAHL SIDOARJO',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2022,
                'fund' => 22400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'RIZKA HADIWIYANTI',
                'title' => 'IMPLEMENTASI EVENT MANAJEMEN SYSTEM PADA KAMPUS BERBASIS SISTEM INFORMASI MANAJEMEN ACARA KAMPUS (SIMARKUS) DI UNIVERSITAS PEMBANGUNAN NASIONAL “VETERAN“ JAWA TIMUR',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2020,
                'fund' => 26500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'OPTIMASI REPRESENTASI DIRI MAHASISWA UPN VETERAN JAWA TIMUR: STUDI PENGEMBANGAN SISTEM INFORMASI PORTOFOLIO DESKRIPSI DIRI',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (TERAPAN)',
                'year' => 2024,
                'fund' => 30000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'MANISAN TOMAT BERKUALITAS TINGGI: PROSES PENGOLAHAN DAN PENERAPAN STANDAR KUALITAS PRODUK',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER BUKU)',
                'year' => 2024,
                'fund' => 7000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'APLIKASI DIGITAL PORTOFOLIO SEBAGAI PERSONAL BRANDING AKADEMIS DI LINGKUNGAN MAHASISWA UPN VETERAN JAWA TIMUR',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA LANJUTAN)',
                'year' => 2023,
                'fund' => 23500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'APLIKASI PUSAT KARIR (PUSAKA) BERBASIS WEBSITE MENGGUNAKAN ARTIFICIAL INTELLIGENCE SEBAGAI SENTRALISASI PEMBINAAN DAN PENGEMBANGAN KARIR MAHASISWA-ALUMNI UPN VETERAN JAWA TIMUR',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2023,
                'fund' => 23800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'ANALISIS PENERIMAAN MOBILE BANKING DALAM PERSPEKTIF',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI NASIONAL)',
                'year' => 2023,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'RANCANG BANGUN SISTEM INFORMASI AKADEMIK SEKOLAH MENGGUNAKAN FRAMEWORK CODEIGNITER SMA TRIMURTI SURABAYA',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2022,
                'fund' => 22300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'INOVASI BRANDING PRODUK UMKM KAMPOENG BATIK JETIS KABUPATEN SIDOARJO BERBASIS KEARIFAN LOKAL UNTUK MENINGKATKAN PEMASARAN PADA ERA DISRUPSI',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2021,
                'fund' => 14200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'PENGEMBANGAN APLIKASI PELAPORAN JALAN BANJIR DENGAN FITUR PEMILIHAN RUTE ALTERNATIF PERJALANAN',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2021,
                'fund' => 23300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ARISTA PRATAMA',
                'title' => 'APLIKASI E-LEARNING BERBASIS BOT TELEGRAM (ER-BOT)',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2020,
                'fund' => 27500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ABDUL REZHA EFRAT NAJAF',
                'title' => 'EKOSISTEM HIJAU DIGITAL DESA WISATA MELALUI ANALISIS KEBERLANJUTAN DAN PEMBUATAN CARBON CALCULATOR',
                'topic_id' => 5,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (TERAPAN)',
                'year' => 2024,
                'fund' => 35000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ABDUL REZHA EFRAT NAJAF',
                'title' => 'PENERAPAN VIRTUAL ASSISTANCE AKADEMIK DAN SKPM (SATUAN KREDIT POIN MAHASISWA) BERBASIS FLOW-BASED CHATBOT DI LINGKUNGAN UPN “VETERAN“ JAWA TIMUR',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2023,
                'fund' => 23800000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ABDUL REZHA EFRAT NAJAF',
                'title' => 'SISTEM INFORMASI BIMBINGAN TUGAS AKHIR MAHASISWA PROGRAM STUDI SISTEM INFORMASI UPN VETERAN JAWA TIMUR',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI NASIONAL)',
                'year' => 2023,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ABDUL REZHA EFRAT NAJAF',
                'title' => 'ANALISIS DAN PERANCANGAN SISTEM MANAJEMEN HUBUNGAN PELANGGAN (CRM) PADA UMKM',
                'topic_id' => 1,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI NASIONAL)',
                'year' => 2023,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANINDO SAKA FITRI',
                'title' => 'STEM INFORMASI MONITORING CAPAIAN PEMBELAJARAN MAHASISWA PROGRAM STUDI SISTEM INFORMASI UPN VETERAN JAWA TIMUR',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2023,
                'fund' => 13500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANINDO SAKA FITRI',
                'title' => 'ANALISIS MATURITY LEVEL KEAMANAN SISTEM INFORMASI DI DISKOMINFO KAB. MOJOKERTO BERDASARKAN STANDAR ISO 27002',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI)',
                'year' => 2022,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANINDO SAKA FITRI',
                'title' => 'NAMED ENTITY RECOGNITION PADA LOWONGAN PEKERJAAN DI INDONESIA MENGGUNAKAN BERT-BASED MODELS',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2016,
                'fund' => 13500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANITA WULANSARI',
                'title' => 'METODE SCRUM PADA PERANCANGAN DAN PENGEMBANGAN SISTEM INFORMASI MANAJEMEN PRAKTIK KERJA LAPANGAN (SIMPEL) UNTUK MENINGKATKAN EFISIENSI DAN EFEKTIVITAS PELAKSANAAN PROGRAM MAGANG PADA PROGRAM STUDI SISTEM INFORMASI',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (PDP)',
                'year' => 2024,
                'fund' => 13500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANITA WULANSARI',
                'title' => 'BUKU AJAR KECAKAPAN PRIBADI (INTERPERSONAL SKILLS) MENJADI PRIBADI UNGGUL BERKARAKTER BELA NEGARA DI ERA DIGITALISASI 5.0',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER BUKU)',
                'year' => 2023,
                'fund' => 7000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANITA WULANSARI',
                'title' => 'ANALISIS KESUKSESAN LAYANAN AKADEMIK DI UPN “VETERAN“ JAWA TIMUR MENGGUNAKAN INFORMATION SYSTEM SUCCESS MODEL (ISSM)',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI NASIONAL)',
                'year' => 2023,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ANITA WULANSARI',
                'title' => '“CLASSIFICATION OF COVID PATIENS BASED ON DETECTION OF LUNG X-RAYS',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI)',
                'year' => 2021,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ASIF FAROQI',
                'title' => 'MENUJU PEMBELAJARAN YANG LEBIH MANDIRI: ADOPSI TEKNOLOGI ARTIFICIAL INTELLIGENCE DAN KESADARAN BELAJAR SISWA SMA NEGERI DI KABUPATEN MOJOKERTO DENGAN PENDEKATAN ACCEPTANCE TECHNOLOGY',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (PENELITIAN SKRIPSI)',
                'year' => 2024,
                'fund' => 10000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ASIF FAROQI',
                'title' => 'PENGUKURAN KEBERLANJUTAN PENERIMAAN E-LEARNING ILMU',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2023,
                'fund' => 12000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ASIF FAROQI',
                'title' => 'APLIKASI PELAPORAN JALAN TERENDAM BANJIR BERBASIS WARGA PADA NAVIGASI BERLALU LINTAS',
                'topic_id' => 4,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2020,
                'fund' => 12000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'NURCAHYO WIBOWO',
                'title' => 'OPTIMALISASI HASIL PERTANIAN BUAH MELON KEBON PAK DOKTER MEMANFAATKAN INTERNET OF THINGS (IOT) UNTUK PENYIRAMAN OTOMATIS SERTA DETEKSI KEBUTUHAN TANAMAN',
                'topic_id' => 6,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (TERAPAN)',
                'year' => 2024,
                'fund' => 30000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'NURCAHYO WIBOWO',
                'title' => 'APLIKASI DETEKSI WAJAH PEROKOK (SIKATROK) SEBAGAI',
                'topic_id' => 6,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2023,
                'fund' => 23000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AMALIA ANJANI ARIFIYANTI',
                'title' => 'LAWNIA CONNECT PLATFORM DIGITAL UNTUK MENGKONEKSIKAN BERBAGAI LAYANAN JASA BERBASIS HUKUM',
                'topic_id' => 4,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (CALON STARTUP)',
                'year' => 2023,
                'fund' => 5000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AMALIA ANJANI ARIFIYANTI',
                'title' => 'Pengembangan Aplikasi Untuk Mengunduh, Mengolah, Dan Menganalisis Data Media Sosial Secara Terintegrasi',
                'topic_id' => 9,
                'funding' => 'Penelitian Kompetitif Nasional (PFR)',
                'year' => 2023,
                'fund' => 96000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AMALIA ANJANI ARIFIYANTI',
                'title' => 'MODEL KOMUNIKASI DAN DESAIN PUBLIKASI DIGITAL STANDARD OPERASIONAL PROSEDUR KEBIJAKAN BAGI DOSEN',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2020,
                'fund' => 11500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AMALIA ANJANI ARIFIYANTI',
                'title' => 'INTELLIGENT-SERVER BERBASIS INTERNET OF THINGS (IOT) UNTUK MONITOR DATA MULTI SENSOR',
                'topic_id' => 7,
                'funding' => 'Penelitian Kompetitif Nasional (PDP/Dosen Pemula)',
                'year' => 2017,
                'fund' => 20000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'SITI MUKAROMA H',
                'title' => 'PEMROGRAMAN VISUAL DATABASE BERBASIS DESKTOP DENGAN PENDEKATAN DIALOG GAMBAR KARTUN',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (PMP)',
                'year' => 2020,
                'fund' => 12000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'SITI MUKAROMA H',
                'title' => 'APLIKASI MONITORING KONVERSI LAHAN DENGAN MENGGUNAKAN GOOGLE EARTH DAN PHP STUDI KASUS KABUPATEN SIDOARJO',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2016,
                'fund' => 16000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'EKA DYAR WAHYUNI',
                'title' => 'SIMARIS NG DAN INTEGRASINYA DENGAN APLIKASI INTERNAL UPN VETERAN JATIM',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2023,
                'fund' => 24000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'EKA DYAR WAHYUNI',
                'title' => 'REPOSITORY PRODUK HUKUM DAN NASKAH DINAS UPN “VETERAN“ JAWA TIMUR',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2022,
                'fund' => 24000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'EKA DYAR WAHYUNI',
                'title' => 'IMPLEMENTASI BUSINESS PROCESS MANAGEMENT USING INFORMATION TECHNOLOGY DI LEMBAGA PENELITIAN DAN PENGABDIAN MASYARAKAT UPNV JATIM',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2021,
                'fund' => 25000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'EKA DYAR WAHYUNI',
                'title' => 'KLASIFIKASI TEKS DENGAN PYTHON',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (PMP)',
                'year' => 2020,
                'fund' => 10000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'EKA DYAR WAHYUNI',
                'title' => 'PEMBUATAN INTELLIGENT COMMUNITY INFORMATION SYSTEMS (ICIS) UNTUK PERTANIAN',
                'topic_id' => 8,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTI)',
                'year' => 2016,
                'fund' => 21000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ERISTYA MAYA SAFITRI',
                'title' => 'DETEKSI GAMBAR BAHASA ISYARAT MENGGUNAKAN METODE CONVOLUTIONAL NEURAL NETWORK (CNN)',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI)',
                'year' => 2022,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ERISTYA MAYA SAFITRI',
                'title' => 'EFEKTIVITAS HASIL BELAJAR MAHASISWA PADA MATA KULIAH BAHASA INDONESIA MELALUI PROJECT BASED LEARNING RUANG LITERASI',
                'topic_id' => 2,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2022,
                'fund' => 12400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ERISTYA MAYA SAFITRI',
                'title' => 'SISTEM INFORMASI MANAJEMEN PRAKTIK KERJA LAPANGAN (STEMPEL)',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISDA)',
                'year' => 2021,
                'fund' => 13500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ERISTYA MAYA SAFITRI',
                'title' => 'Bali Backpacker sebagai Platform Panduan Lengkap Berwisata ke Bali dengan Dwibahasa.',
                'topic_id' => 5,
                'funding' => 'Penelitian Penugasan (KKS)',
                'year' => 2021,
                'fund' => 59774500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'ERISTYA MAYA SAFITRI',
                'title' => 'CRITICAL DATA ANALYSIS OF COVID-19 SPREADING IN INDONESIA TO MEASURE THE READINESS OF NEW-NORMAL POLICY',
                'topic_id' => 4,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI JURNAL INTERNASIONAL BEREPUTASI)',
                'year' => 2021,
                'fund' => 10000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AGUNG BRASTAMA',
                'title' => 'IMPLEMENTASI ENHANCED SPRAY ROUTING PROTOCOL UNTUK VDTN PADA SKENARIO SURABAYA SMART CITY',
                'topic_id' => 3,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (UBER PUBLIKASI NASIONAL)',
                'year' => 2023,
                'fund' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AGUNG BRASTAMA',
                'title' => 'VISUALISASI JARINGAN KOMUNIKASI MEDIA SOSIAL TWITTER 6 PTN DI JAWA TIMUR',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISET TERAPAN)',
                'year' => 2022,
                'fund' => 22700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AGUNG BRASTAMA',
                'title' => 'RANCANG BANGUN PERALATAN DETEKSI BENCANA KEBAKARAN AKIBAT HUBUNG SINGKAT LISTRIK SECARA ONLINE BERBASIS SMART PHONE',
                'topic_id' => 9,
                'funding' => 'Penelitian Desentralisasi (PTUPT)',
                'year' => 2020,
                'fund' => 223000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'AGUNG BRASTAMA',
                'title' => 'VISUALISASI DAN INTERPRETASI JARINGAN MEDIA SOSIAL TWITTER PADA GENERASI MILENIAL',
                'topic_id' => 9,
                'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (RISTER)',
                'year' => 2020,
                'fund' => 27000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'author' => 'MOHAMAD IRWAN AFANDI',
                'title' => 'Pembuatan Intelligent FISHCARELAB System (IFS) sebagai Sistem Pembudidayaan Ikan Jarak Jauh Berbasis Internet',
                'topic_id' => 9,
                'funding' => 'Penelitian Desentralisasi (PTUPT)',
                'year' => 2017,
                'fund' => 164000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        $skripsi = [
            [
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '210820100005',
                    'angkatan' => 2021,
                    'author' => 'Audy Fitri Ariani',
                    'title' => 'Rancang Bangun Sistem Reservasi Antrean Dan Catatan Perawatan Berbasis Android (Studi Kasus: Salon Kezia Pasuruan)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/35744/',
                    'youtubeLink' => 'https://youtu.be/1pJgZW5v40k',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010194',
                    'angkatan' => 2021,
                    'author' => 'Amalia Safira',
                    'title' => 'Rancang Bangun Sistem Informasi CRM Untuk Optimasi Layanan Berbasis Web Dengan Metode RAD Di Surya Kencana Stationery & Copy Center',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/36091/',
                    'youtubeLink' => 'https://youtu.be/LbKVjFdiQQU',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010108',
                    'angkatan' => 2021,
                    'author' => 'Sayyidah Nafisah',
                    'title' => 'PREDIKSI PRODUKSI SONGKOK MENGGUNAKAN METODE ARIMA (AUTOREGRESSIVE INTEGRATED MOVING AVERAGE) DAN EXPONENTIAL SMOOTHING PADA TEBU MAS GRESIK',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/37073/',
                    'youtubeLink' => 'https://youtu.be/12xcL02NOWA',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010124',
                    'angkatan' => 2021,
                    'author' => 'Taufiq Arinta',
                    'title' => 'Rancang Bangun Sistem Informasi Pencatatan Transaksi Penjualan dan Gaji Karyawan Menggunakan Metode Scrum',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/38280/',
                    'youtubeLink' => 'https://youtu.be/iKiPa4INsw',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010004',
                    'angkatan' => 2021,
                    'author' => 'Moch. Rezeki Setiawan',
                    'title' => 'RANCANG BANGUN SISTEM INFORMASI STORE MANAGEMENT SYSTEM BERBASIS WEBSITE MENGGUNAKAN FRAMEWORK LARAVEL DENGAN METODE AGILE (STUDI KASUS UMKM TOKO KELONTONG JALI)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/35200/',
                    'youtubeLink' => 'https://youtu.be/Ndkvd5tQrDk',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '19082010040',
                    'angkatan' => 2019,
                    'author' => 'Muh. Rizky Abwiafa Rulyawan',
                    'title' => 'Rancang Bangun Gamifikasi Latihan Mandiri Siswa SMA dengan RPG',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/34579/',
                    'youtubeLink' => 'https://youtu.be/dXRJKbQQ61c',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010068',
                    'angkatan' => 2021,
                    'author' => 'Moh Azzam Priyanto',
                    'title' => 'Rancang Bangun Aplikasi Bank Sampah Kencana Surabaya Berbasis Android Menggunakan Metode Rapid Application Development',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 3,
                    'repositoryLink' => 'https://repository.upnjatim.ac.id/36442/',
                    'youtubeLink' => 'https://youtu.be/zb0hKOq_UFU',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2025,
                    'npm' => '21082010065',
                    'angkatan' => 2021,
                    'author' => 'Izra Noor Zahara Aliya',
                    'title' => 'SPK PRIORITAS PEMBANGUNAN DESA RENGEL',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 4,
                    'repositoryLink' => null,
                    'youtubeLink' => 'https://youtu.be/38j3V784LYM',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010069',
                    'angkatan' => 2015,
                    'author' => 'DELLA NOVITASARI',
                    'title' => 'IDENTIFIKASI KESUKSESAN PENGGUNAAN SISTEM APLIKASI PENGADUAN DAN KELUHAN TERPADU (APKT) (STUDI KASUS: PT.PLN (PERSERO) DI JEMBER)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010109',
                    'angkatan' => 2015,
                    'author' => 'ADAM SETYAWAN LIBRIANTO',
                    'title' => 'ANALISIS KESUKSESAN APLIKASI MOBILE PERSEBAYA SELAMANYA DENGAN PENDEKATAN MODEL DELONE AND MCLEAN',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010074',
                    'angkatan' => 2015,
                    'author' => 'VICKY SURYA PRIHARTANTO. A',
                    'title' => 'RANCANG BANGUN SISTEM MONITORING INVENTORY BARANG BERBASIS WEBSITE (Studi Kasus: PT. Oelangan Karya Etam)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010011',
                    'angkatan' => 2015,
                    'author' => 'MOCHAMMAD AGUNG HIDAYAT',
                    'title' => 'RANCANG BANGUN PERIZINAN LINGKUNGAN BERBASIS WEB. (STUDI KASUS: DINAS LINGKUNGAN HIDUP PROVINSI JAWA TIMUR)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 3,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010085',
                    'angkatan' => 2015,
                    'author' => 'BERGAS WASENANTO',
                    'title' => 'SISTEM PAKAR PENENTUAN TANAMAN OBAT HERBAL UNTUK PENYAKIT DEGENERATIF MENGGUNAKAN METODE FORWARD CHAINING',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 6,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010115',
                    'angkatan' => 2015,
                    'author' => 'MUHAMMAD IMAM ADI NUGROHO',
                    'title' => 'APLIKASI PENCATATAN PEMBELIAN DAN PENJUALAN UKM (USAHA KECIL DAN MIKRO) BERBASIS ANDROID',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010099',
                    'angkatan' => 2015,
                    'author' => 'Syntia Dwi Wahyuningtias',
                    'title' => 'ANALISIS PERSEPSI PELANGGAN RESTORAN CEPAT SAJI PADA TWITTER MENGGUNAKAN SUPPORT VECTOR MACHINE',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010066',
                    'angkatan' => 2015,
                    'author' => 'Ahmad Makky Zamzami',
                    'title' => 'PENGEMBANGAN FITUR SISTEM INFORMASI MONITORING SANTRI PADA WEB MBI AMANATUL UMMAH MOJOKERTO',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010035',
                    'angkatan' => 2015,
                    'author' => 'Muhammad Farrel Achrifiansyah',
                    'title' => 'RANCANG BANGUN SISTEM INFORMASI AKADEMIK BERBASIS WEB (Studi Kasus: SDN Kalirungkut IV 580 Surabaya)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1335010075',
                    'angkatan' => 2013,
                    'author' => 'cipta budi prakasa',
                    'title' => 'aplikasi raport online berbasis web (studi kasus : SMK Antartika 1 Sidoarjo)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010065',
                    'angkatan' => 2015,
                    'author' => 'FARIZ LASMARGO NENDRA WONO',
                    'title' => 'Sistem informasi Penilaian angka kredit dan pengajuan kenaikan jabatan untuk Jabatan Fungsional Sandiman (Studi Kasus: Dinas Komunikasi dan Informatika Provinsi Jawa Timur)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1535010081',
                    'angkatan' => 2015,
                    'author' => 'ANGGA DANI',
                    'title' => 'RANCANG BANGUN BISNIS MODEL DAN APLIKASI SOSIAL PRENEUR BANK JELANTAH BERBASIS WEBSITE DAN MOBILE',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2019,
                    'npm' => '1335010068',
                    'angkatan' => 2013,
                    'author' => 'EKA SAPUTRA',
                    'title' => 'PENGEMBANGAN SISTEM INFORMASI PEMESANAN PAKET WISATA BERBASIS WEB (STUDI KASUS AREK ASIK ADVENTURE TRAVEL)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 5,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010036',
                    'angkatan' => 2015,
                    'author' => 'WAHYU IMAM SYAFII',
                    'title' => 'RANCANG BANGUN SISTEM INFORMASI SURAT KELUAR BERBASIS DEKSTOP DI BANK BTN KCP RUNGKUT',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010017',
                    'angkatan' => 2015,
                    'author' => 'RIOWALDY INDRAWAN',
                    'title' => 'RANCANG BANGUN PLATFORM PEMBELAJARAN DENGAN METODE BLENDED LEARNING BERBASIS MULTIMEDIA',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010084',
                    'angkatan' => 2015,
                    'author' => 'Joko Waluyo Jati',
                    'title' => 'Sistem Informasi Akuntansi pada CV PELANGI (Rex\'s) Meggunakan Framework Laravel',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010021',
                    'angkatan' => 2015,
                    'author' => 'ADE SATRIA KURNIAWAN',
                    'title' => 'ANALISIS PURCHASE INTENTION PADA INSTAGRAM PT. KINETIC DIGITAL INDONESIA DENGAN MODEL PERSAMAAN STRUKTURAL',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010019',
                    'angkatan' => 2015,
                    'author' => 'HIMAS ADIN NUGROHO',
                    'title' => 'SISTEM INFORMASI EKSEKUTIF BERBASIS WEB DENGAN FRAMEWORK CODEIGNITER (STUDI KASUS: PT SAMUDERA SARANA LOGISTIK)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010080',
                    'angkatan' => 2016,
                    'author' => 'ISNI YUNIAR FAJARATRI',
                    'title' => 'PENGUKURAN KESUKSESAN PENERAPAN APLIKASI TRANSPORTASIKU MENGGUNAKAN ISSM DELONE MCLEAN PADA DINAS PERHUBUNGAN SURABAYA',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010009',
                    'angkatan' => 2016,
                    'author' => 'Dannie M. Mulay Junior',
                    'title' => 'Pengukuran dan Analisis Faktor-Faktor Keberhasilan pada Web Akademik Mahasiswa di Sekolah Tinggi Ilmu Ekonomi Indonesia Surabaya',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010033',
                    'angkatan' => 2016,
                    'author' => 'Dwi Rachmat Mulyo Aji',
                    'title' => 'e-marketplace Universitas Pembangunan Nasional "Veteran" Jawa Timur',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010027',
                    'angkatan' => 2016,
                    'author' => 'EGA FEBRI DHARMAWAN',
                    'title' => 'ANALISIS SENTIMEN PENGGUNA SMARTPHONE PADA TWITTER DI INDONESIA',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010017',
                    'angkatan' => 2016,
                    'author' => 'CYNDYA NANDHANY',
                    'title' => 'ANALISIS MATURITY LEVEL LAYANAN DAN PRODUKTIVITAS SUMBER DAYA MANUSIA BERDASARKAN BUSINESS GOAL 15 COBIT 4.1 (STUDI KASUS: DINAS KOMUNIKASI DAN INFORMATIΚΑ PROVINSI JAWA TIMUR)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010072',
                    'angkatan' => 2016,
                    'author' => 'NAMIRA ABDA TAQIYA',
                    'title' => 'ANALISIS TINGKAT KEMATANGAN SISTEM PEMERINTAHAN BERBASIS ELEKTRONIK (SPBE) BERDASARKAN BUSINESS GOAL 14 COBIT 4.1. (STUDI KASUS: DINAS KOMUNIKASI DAN INFORMATIKA JAWA TIMUR)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010058',
                    'angkatan' => 2016,
                    'author' => 'TITA AYU ROSPRICILIA',
                    'title' => 'Operational and Analytical Customer Relationship Management pada CV Tita Jaya',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010014',
                    'angkatan' => 2016,
                    'author' => 'YOLANDA YODISTINA',
                    'title' => 'Analisis Faktor Perilaku Penggunaan Aplikasi Ujian Online Berbasis Moodle Menggunakan UTAUT Pada SMPN 1 Taman',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010007',
                    'angkatan' => 2016,
                    'author' => 'RETNO NIELISA SUPANGAT',
                    'title' => 'SISTEM INFORMASI KLINIK BERBASIS WEB (STUDI KASUS: KLINIK dr. ANDRE SIDOARJO)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 6,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010078',
                    'angkatan' => 2016,
                    'author' => 'Achmad Abdul Rohim',
                    'title' => 'Analisis Faktor-Faktor Yang Mempengaruhi Penggunaan Aplikasi Persebaya Selamanya Menggunakan UTAUT',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010079',
                    'angkatan' => 2016,
                    'author' => 'MUHAMMAD REZA FATAHILLAH',
                    'title' => 'MANAJEMEN JARINGAN POINT TO MULTIPOINT PADA PERGUDANGAN BAGIAN LAYANAN PENGADAAN DAN PENGELOLAAN ASET (LP2A) PEMERINTAН КОТА SURABAYA',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 4,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010045',
                    'angkatan' => 2015,
                    'author' => 'DIMAS AGUNG PRABOWO',
                    'title' => 'PROTOTYPE SISTEM INFORMASI EKSEKUTIF AKADEMIK MENGGUNAKAN DATA WAREHOUSE DAN AD-HOC QUERY PADA KAMPUS X',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010065',
                    'angkatan' => 2016,
                    'author' => 'ANNISA SAFRINA PRASETYANIN GRUM',
                    'title' => 'ANALISIS FAKTOR PENGGUNAAN LAYANAN RAPOR ONLINE DI SURABAYA (STUDI KASUS : WWW.RAPORKU.NET)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1335010048',
                    'angkatan' => 2013,
                    'author' => 'SHOLEH ABUBAKAR ALHAMID',
                    'title' => 'Analisis Faktor yang Mempengaruhi Penjual dalam Memilih Platform Jual-Beli Online (Studi Kasus: Aplikasi SHOPee)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 1,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010038',
                    'angkatan' => 2016,
                    'author' => 'Mohammad Nur Rizal',
                    'title' => 'ANALISIS TINGKAT KEMATANGAN BERDASARKAN PERSPEKTIF PELANGGAN DALAM MENINGKATKATKAN PENYAJIAN PRODUK dan JASA YANG KOMPETTIF MENGGUNAKAN STANDAR COBIT 4.1 Studi Kasus : Rumah Sakit Umum Haji Surabaya',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010040',
                    'angkatan' => 2016,
                    'author' => 'ABI ZAKARIA',
                    'title' => 'ANALISIS TINGKAT KEMATANGAN MENGGUNAKAN FRAMEWORK COBIT 4.1 PADA PERSPEKTIF PELANGGAN B.G. 8 (Studi kasus: INSTALASI SIM Rumah Sakit Haji Sukolilo Surabaya)',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010083',
                    'angkatan' => 2015,
                    'author' => 'RIZWAN HANAFI',
                    'title' => 'SISTEM INFORMASI BIMBINGAN KONSELING BERBASIS WEB (STUDI KASUS: SMK NEGERI 1 MOJOAGUNG)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010005',
                    'angkatan' => 2016,
                    'author' => 'ADIAN RISWANDHA',
                    'title' => 'RANCANG BANGUN SISTEM INFORMASI PERENCANAAN DAN PELAPORAN KEGIATAN DENGAN FITUR PEMESANAN KONSUMSI BERBASIS WEB DAN MOBILE (Studi kasus: Universitas Pembangunan Nasional "Veteran" Jawa Timur)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1335010042',
                    'angkatan' => 2013,
                    'author' => 'ANGGARDA DEWANTARA',
                    'title' => 'SISTEM INFORMASI PEMESANAN PAKET FOTO BERBASIS WEB',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1335010085',
                    'angkatan' => 2013,
                    'author' => 'ACHMAD FITRI YANUAR',
                    'title' => 'SISTEM INFORMASI AKUNTANSI BENGKEL (STUDI KASUS TON\'S MOTOR)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010010',
                    'angkatan' => 2015,
                    'author' => 'Angga Zakaria',
                    'title' => 'Sistem Informasi Perpustakaan (Studi Kasus : Perpustakaan Medayu Agung Surabaya)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010025',
                    'angkatan' => 2015,
                    'author' => 'AHMAD FADHILAH',
                    'title' => 'Sistem Informasi Pemesanan Katering Dengan Fitur Live Chat Berbasis Web (Studi Kasus: Katering Melati Serelo Surabaya)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010093',
                    'angkatan' => 2015,
                    'author' => 'ADE PRASETYA INDRA SETIAWAN',
                    'title' => 'RANCANG BANGUN SISTEM INFORMASI AKADEMIK BERBASIS WEB (STUDI KASUS: SMK PGRI 1 LAMONGAN)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1435010061',
                    'angkatan' => 2014,
                    'author' => 'Riswandha Aditama',
                    'title' => 'Analisis Faktor Kinerja Mahasiswa Dalam Memanfaatkan E-learning (studi kasus: UPN "Veteran" Jawa Timur',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010003',
                    'angkatan' => 2016,
                    'author' => 'EMILIA ROSA',
                    'title' => 'MEDIA EDUKASI "EXERXAM" SEBAGAI APLIKASI PENGEMBANGAN FITUR E-LEARNING BERDASARKAN ALGORITMA ADAPTIVE TEST DAN FISHER YATES (STUDI KASUS: SMA NEGERI 1 SUKODADI - LAMONGAN)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010011',
                    'angkatan' => 2016,
                    'author' => 'RAHMAH PUTRI FARISKA',
                    'title' => 'SISTEM PAKAR ORTHODONTI PADA ANALISIS KLINIS KASUS MALOKLUSI MENGGUNAKAN METODE FORWARD CHAINING DENGAN CERTAINTY FACTOR',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010004',
                    'angkatan' => 2016,
                    'author' => 'ERICA MAS\'UDAH',
                    'title' => 'ANALISIS SENTIMEN PEMINDAHAN IBU KOTA INDONESIA PADA TWITTER DENGAN MENGGUNAKAN METODE NAIVE BAYES',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010019',
                    'angkatan' => 2016,
                    'author' => 'AHMAD QUSHAY AL BARRA',
                    'title' => 'Sistem Pendukung Keputusan Pemilihan KDR & PA Menggunakan Metode Profile Matching',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010034',
                    'angkatan' => 2016,
                    'author' => 'Qonita',
                    'title' => 'KLASIFIKASI TWEET PADA AKUN TWITTER SUARA SURABAYA DENGAN MENGGUNAKAN METODE NAIVE BAYES',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010027',
                    'angkatan' => 2016,
                    'author' => 'AYU BUDY HEROWATI',
                    'title' => 'SISTEM PENDUKUNG KEPUTUSAN PERAWATAN ORTHODONTIK PADA KASUS BORDERLINE MENGGUNAKAN METODE PROFILE MATCHING SKRIPSI',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010027',
                    'angkatan' => 2015,
                    'author' => 'Abdul Hanif Al-atho\'illah',
                    'title' => 'Sistem Klasifikasi Safety Product Menggunakan Text Mining',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010063',
                    'angkatan' => 2016,
                    'author' => 'GITA ISLAMIWATY SUHERLAN',
                    'title' => 'ANALISIS KUALITAS LAYANAN APLIKASI MY TELKOMSEL MENGGUNAKAN METODE E-SERVQUAL PADA PENGGUNA TELKOMSEL DI SURABAYA',
                    'interest' => 'Manajemen Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010025',
                    'angkatan' => 2016,
                    'author' => 'Rizky Dwi Pratiwi',
                    'title' => 'SISTEM INFORMASI MANAJAMEN ADMINISTRASI LEMBAGA BIMBINGAN BELAJAR',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 2,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1635010075',
                    'angkatan' => 2016,
                    'author' => 'MOHAMAD RIZA RAMADHANI ODING',
                    'title' => 'SISTEM INFORMASI PERAMALAN PRODUKSI MENGGUNAKAN METODE SINGLE EXPONENTIAL SMOOTHING (STUDI KASUS: PT.MESHINDO ALLOY WHEEL)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id'=> 1,
                    'year' => 2020,
                    'npm' => '1535010110',
                    'angkatan' => 2015,
                    'author' => 'MOCHAMMAD RIDHO ILYASA',
                    'title' => 'RANCANG BANGUN MARKETPLACE EVENT DENGAN KONSEP CROWDSOURCING (MODUL PENYELENGGARA & PESERTA EVENT)',
                    'interest' => 'Solusi Sistem Informasi',
                    'topic_id' => 9,
                    'repositoryLink' => null,
                    'youtubeLink' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        ];

        $pengmas = [
            [
                [
                    'category_id' => 3,
                    'author' => 'NURCAHYO WIBOWO',
                    'title' => 'PROSES FERMENTASI AN-AEROBIK LIMBAH KOTORAN TERNAK MENJADI PUPUK ORGANIK UNTUK MENDUKUNG KELESTARIAN LINGUNGAN DI PEDESAAN',
                    'topic_id' => 9,
                    'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (KKN - TEMATIK)',
                    'year' => 2016,
                    'fund' => 29000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id' => 3,
                    'author' => 'AMALIA ANJANI ARIFIYANTI',
                    'title' => 'PKM INDUSTRI RUMAHAN PRODUK KREATIF',
                    'topic_id' => 9,
                    'funding' => 'Pengabdian Kepada Masyarakat Kompetitif Nasional (PKM)',
                    'year' => 2018,
                    'fund' => 43000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id' => 3,
                    'author' => 'EKA DYAR WAHYUNI',
                    'title' => 'PEMBERDAYAAN MASYARAKAT BEPOLA PIKIR KREATIF DAN GEMAR MENCIPTA MELALUI PEMBELAJARAN ILMU KOMPUTER DASAR DI DESA MASANGAN KULON, KECAMATAN SUKODONO, KABUPATEN SIDOARJO JAWA TIMUR',
                    'topic_id' => 9,
                    'funding' => 'DIPA UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR (KKN - TEMATIK)',
                    'year' => 2016,
                    'fund' => 28000000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'category_id' => 3,
                    'author' => 'MOHAMAD IRWAN AFANDI',
                    'title' => 'PEMBERDAYAAN MASYARAKAT MENUJU DESA MAJU DAN MANDIRI BERBASIS TEKNOLOGI INFORMASI',
                    'topic_id' => 9,
                    'funding' => 'Pengabdian Kepada Masyarakat Kompetitif Nasional (KKN-PPM)',
                    'year' => 2015,
                    'fund' => 57500000,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        ];

        // Research::insert([$penelitian, $skripsi, $pengmas]);
        Research::insert($penelitian);
        Research::insert(array_merge(...$skripsi));
        Research::insert(array_merge(...$pengmas));
    }
}
